# Generated by Django 5.0 on 2023-12-23 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Post_Image', models.ImageField(null=True, upload_to='media/postimages')),
                ('Post_Title', models.CharField(max_length=100)),
                ('Post_Description', models.TextField(max_length=5000)),
                ('Permission', models.BooleanField(default=False)),
                ('see_more', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('Created_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
