# Generated by Django 5.0 on 2023-12-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('blogger', 'Blogger')], max_length=120),
        ),
    ]
