# Generated by Django 5.0 on 2023-12-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_custom_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('blogger', 'Blogger'), ('admin', 'Admin')], max_length=120),
        ),
    ]
